name: Actions Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: run makefile
        run: make -B bin/stage3
